[package]
name = "python_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
parser_core = { path = "../../core" }
tree-sitter = { workspace = true }
tree-sitter-python = { workspace = true }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
