[package]
name = "parser_engine_markdown"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = { workspace = true }
tree-sitter-md = { workspace = true }
parser_core = { path = "../../core" }