name = "singularity"
version = "0.1.0"

description = "HTDAG - Hierarchical Task DAG for autonomous task decomposition"

target = "erlang"

[dependencies]
gleam_stdlib = "~> 0.65.0"

[dev-dependencies]
gleeunit = "~> 1.0"
