[package]
name = "parser_engine_dockerfile"
version = "0.1.0"
edition = "2021"

[dependencies]
tree-sitter = { workspace = true }
tree-sitter-dockerfile = "0.2.0"
parser_core = { path = "../../core" }