apiVersion: v1
kind: Service
metadata:
  name: seed-agent
spec:
  selector:
    app: seed-agent
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: seed-agent-headless
spec:
  clusterIP: None
  selector:
    app: seed-agent
  publishNotReadyAddresses: true
  ports:
    - name: epmd
      port: 4369
      targetPort: 4369
    - name: dist
      port: 9000
      targetPort: 9000
