[package]
name = "quality_service"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Quality NATS service"

[[bin]]
name = "quality_service"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
tokio = { workspace = true, features = ["full"] }
async-nats = "0.33"
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
